# Generated by Django 4.1.2 on 2022-10-25 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikelnummer', models.IntegerField()),
                ('bezeichnung', models.CharField(max_length=255)),
                ('anzahl', models.IntegerField()),
                ('kategorie', models.CharField(max_length=150)),
                ('lieferant', models.CharField(max_length=60)),
                ('ekpreis', models.FloatField()),
                ('vkpreis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lagernummer', models.IntegerField()),
                ('halle', models.IntegerField()),
                ('Etage', models.IntegerField()),
                ('Regal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='kennzahlen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxbestand', models.IntegerField()),
                ('minbestand', models.IntegerField()),
                ('meldebestand', models.IntegerField()),
                ('umsatz', models.FloatField()),
                ('gewinn', models.FloatField()),
                ('abgänge', models.IntegerField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LagerApp.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LagerApp.storage'),
        ),
    ]
