# Generated by Django 4.1.2 on 2022-10-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LagerApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kennzahlen',
        ),
    ]
