# Generated by Django 4.1.2 on 2022-10-25 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LagerApp', '0002_delete_kennzahlen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kennzahlen',
            fields=[
                ('maxbestand', models.IntegerField()),
                ('minbestand', models.IntegerField()),
                ('meldebestand', models.IntegerField()),
                ('umsatz', models.FloatField()),
                ('gewinn', models.FloatField()),
                ('abgänge', models.IntegerField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='LagerApp.article')),
            ],
        ),
    ]
